# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: ms-time-line-starter
spec:
  enabled: true
  requires: ">=2.11.0"
  author:
    name: 新疆萌森软件开发工作室
    website: https://blog.lifebus.top
  logo: logo.png
  homepage: https://blog.lifebus.top
  repo: https://github.com/QYG2297248353/halo-time-line-plugin
  issues: https://github.com/QYG2297248353/halo-time-line-plugin/issues
  displayName: "时间线"
  description: "时间线，记录你的生活点滴"
